apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsutils
  labels:
    app: dnsutils
spec:
  selector:
    matchLabels:
      app: dnsutils
  template:
    metadata:
      labels:
        app: dnsutils
    spec:
      containers:
      - image: k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
        name: dnsutils
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        command:
         - sleep
         - "3600"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
